### ISSUE TITLE
Getting error when compiling

### ISSUE THREAD

**Issue by JEEEZY** [youngqqcn/QBlockChainNotes#7]
Hi youngqqcn, do you have discord or Skype? I am having trouble compiling Bitcoin SV at the end.

**Comment by JEEEZY** [comment]
I can't use bitcoin-cli.

"bitcoin-cli: error while loading shared libraries: libboost_system.so.1.53.0: cannot open shared object file: No such file or directory".

Thank you.

**Comment by youngqqcn** [comment]
CentOS 7 
> https://github.com/youngqqcn/QBlockChainNotes/blob/master/BTC%E7%B3%BB%E5%B1%B1%E5%AF%A8%E5%B8%81/7.%E7%BC%96%E8%AF%91BSV%E6%BA%90%E7%A0%81(v1.0.1).md
